<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Workers.csproj" />
    <ProjectReference Include="..\..\..\..\src\Compiler\Compiler.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>
  <Import Project="..\..\..\..\src\Build\Workers.targets" />
</Project>
