name = "workers-example-r2-binding"
main = "dist/worker.js"
compatibility_date = "2026-06-30"

[build]
command = "dotnet publish -c Release -p:NuGetAudit=false"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "workers-example-bucket"
