<Project>
  <Import
    Project="$(NuGetPackageRoot)\microsoft.net.illink.tasks\10.0.8\build\Microsoft.NET.ILLink.Tasks.props"
    Condition="'$(ILLinkTargetsPath)' == '' and Exists('$(NuGetPackageRoot)\microsoft.net.illink.tasks\10.0.8\build\Microsoft.NET.ILLink.Tasks.props')" />

  <PropertyGroup>
    <JsonSerializerIsReflectionEnabledByDefault Condition="'$(JsonSerializerIsReflectionEnabledByDefault)' == ''">true</JsonSerializerIsReflectionEnabledByDefault>
    <BlazorWebAssemblyJiterpreter Condition="'$(BlazorWebAssemblyJiterpreter)' == ''">false</BlazorWebAssemblyJiterpreter>
    <IsTrimmable Condition="'$(IsTrimmable)' == ''">true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'browser-wasm'">
    <OutputType>Exe</OutputType>
    <InvariantGlobalization Condition="'$(InvariantGlobalization)' == '' and '$(WorkersInvariantGlobalization)' != 'false'">true</InvariantGlobalization>
    <WasmMainJSPath Condition="'$(WasmMainJSPath)' == ''">$(MSBuildThisFileDirectory)Workers.main.js</WasmMainJSPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'browser-wasm' and '$(WorkersGenerateProgram)' != 'false'">
    <Compile Include="$(MSBuildThisFileDirectory)Workers.Program.cs" Link="Workers.Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="$(AssemblyName)" />
    <TrimmerRootDescriptor Include="$(MSBuildThisFileDirectory)Workers.ILLink.Descriptors.xml" />
  </ItemGroup>
</Project>
