using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

internal sealed partial class JavaScriptEmitter
{
    private readonly StringBuilder _output = new();
    private readonly CSharpCompilation _compilation;
    private readonly GeneratedNameAllocator _names = new();
    private readonly HelperRegistry _helpers;
    private readonly ImportRegistry _imports;
    private readonly Dictionary<ISymbol, string> _userIdentifiers = new(SymbolEqualityComparer.Default);
    private readonly Dictionary<IMethodSymbol, string> _userMethods = new(SymbolEqualityComparer.Default);
    private readonly Queue<IMethodSymbol> _pendingUserMethods = new();
    private readonly HashSet<IMethodSymbol> _emittedUserMethods = new(SymbolEqualityComparer.Default);
    private readonly Stack<string> _caughtExceptions = new();
    private SemanticModel _model = null!;
    private JavaScriptEmitter(CSharpCompilation compilation)
    {
        _compilation = compilation;
        _helpers = new HelperRegistry(_names);
        _imports = new ImportRegistry(_names);
    }

    public static string Emit(CSharpCompilation compilation)
    {
        var program = WorkerDiscovery.Discover(compilation);
        var emitter = new JavaScriptEmitter(compilation);

        emitter._output.AppendLine("// Generated by Workers.Compiler.");
        foreach (var htmlHandler in program.HtmlHandlers)
            emitter.EmitHtmlHandler(htmlHandler);
        foreach (var durableObject in program.DurableObjects)
            emitter.EmitDurableObject(durableObject);
        foreach (var workerEntrypoint in program.WorkerEntrypoints)
            emitter.EmitWorkerEntrypoint(workerEntrypoint);
        foreach (var handler in program.Events)
            emitter.EmitHandler(handler.Name, handler.Method);
        emitter.EmitUserMethods();

        emitter._output.Append(emitter._helpers.Emit());

        if (program.Events.Count != 0)
            emitter._output.Append("export default { ")
                .Append(string.Join(", ", program.Events.Select(handler => $"{handler.Name}: {emitter.EventName(handler.Name)}")))
                .AppendLine(" };");
        return emitter._imports.Emit() + emitter._output;
    }

}
