using static BindingIntrinsicRegistry;

internal static class
DurableObjectIntrinsics
{
    public static IReadOnlyDictionary<(string Type, string Method), BindingIntrinsic> Methods { get; } =
        new Dictionary<(string Type, string Method), BindingIntrinsic>
        {
            [Key("Workers.IDurableObjectNamespace", "IdFromNameAsync")] = Direct("idFromName"),
            [Key("Workers.IDurableObjectNamespace", "IdFromStringAsync")] = Direct("idFromString"),
            [Key("Workers.IDurableObjectNamespace", "NewUniqueIdAsync")] = Direct("newUniqueId"),
            [Key("Workers.IDurableObjectNamespace", "Get")] = Direct("get"),
            [Key("Workers.IDurableObjectNamespace", "GetByName")] = Direct("getByName"),
            [Key("Workers.IDurableObjectStub", "InvokeAsync")] = new("", BindingIntrinsicKind.ServiceRpc),
            [Key("Workers.DurableObjectId", "ToString")] = Direct("toString"),
            [Key("Workers.DurableObjectState", "WaitUntil")] = Direct("waitUntil"),
            [Key("Workers.DurableObjectState", "BlockConcurrencyWhileAsync")] = Direct("blockConcurrencyWhile"),
            [Key("Workers.DurableObjectState", "Abort")] = Direct("abort"),
            [Key("Workers.DurableObjectState", "AcceptWebSocket")] = Direct("acceptWebSocket"),
            [Key("Workers.DurableObjectState", "GetWebSockets")] = Direct("getWebSockets"),
            [Key("Workers.DurableObjectState", "GetTags")] = Direct("getTags"),
            [Key("Workers.DurableObjectState", "SetWebSocketAutoResponse")] = Direct("setWebSocketAutoResponse"),
            [Key("Workers.DurableObjectState", "GetWebSocketAutoResponse")] = Direct("getWebSocketAutoResponse"),
            [Key("Workers.DurableObjectState", "GetWebSocketAutoResponseTimestamp")] = Direct("getWebSocketAutoResponseTimestamp"),
            [Key("Workers.DurableObjectState", "SetHibernatableWebSocketEventTimeout")] = Direct("setHibernatableWebSocketEventTimeout"),
            [Key("Workers.DurableObjectState", "GetHibernatableWebSocketEventTimeout")] = Direct("getHibernatableWebSocketEventTimeout"),
            [Key("Workers.DurableObjectStorage", "GetAsync")] = new("get", BindingIntrinsicKind.DurableObjectGet),
            [Key("Workers.DurableObjectStorage", "PutAsync")] = Direct("put"),
            [Key("Workers.DurableObjectStorage", "DeleteAsync")] = Direct("delete"),
            [Key("Workers.DurableObjectStorage", "DeleteAllAsync")] = Direct("deleteAll"),
            [Key("Workers.DurableObjectStorage", "GetAlarmAsync")] = Direct("getAlarm"),
            [Key("Workers.DurableObjectStorage", "SetAlarmAsync")] = Direct("setAlarm"),
            [Key("Workers.DurableObjectStorage", "DeleteAlarmAsync")] = Direct("deleteAlarm"),
            [Key("Workers.DurableObjectStorage", "GetCurrentBookmarkAsync")] = Direct("getCurrentBookmark"),
            [Key("Workers.DurableObjectStorage", "GetBookmarkForTimeAsync")] = Direct("getBookmarkForTime"),
            [Key("Workers.DurableObjectStorage", "OnNextSessionRestoreBookmarkAsync")] = Direct("onNextSessionRestoreBookmark"),
            [Key("Workers.DurableObjectStorage", "SyncAsync")] = Direct("sync"),
            [Key("Workers.DurableObjectSqlStorage", "Prepare")] = Direct("exec"),
            [Key("Workers.DurableObjectSqlStatement", "Bind")] = Direct("bind"),
            [Key("Workers.DurableObjectSqlStatement", "AllAsync")] = Direct("all"),
            [Key("Workers.DurableObjectSqlStatement", "OneAsync")] = Direct("one"),
            [Key("Workers.DurableObjectSqlStatement", "RawAsync")] = Direct("raw"),
            [Key("Workers.DurableObjectSqlStatement", "OpenCursorAsync")] = Direct("cursor"),
            [Key("Workers.DurableObjectSqlStorage", "TransactionSyncRawAsync")] = Direct("transactionSync"),
            [Key("Workers.DurableObjectSqlCursor<T>", "NextAsync")] = Direct("next"),
            [Key("Workers.DurableObjectSqlCursor<T>", "ReadAllAsync")] = Direct("toArray"),
            [Key("Workers.DurableObjectSqlCursor<T>", "DisposeAsync")] = new("", BindingIntrinsicKind.Dispose),
            [Key("Workers.DurableObjectStorage", "ListAsync")] = new("list", BindingIntrinsicKind.DictionaryObject),
            [Key("Workers.DurableObjectStorage", "TransactionAsync")] = Direct("transaction"),
            [Key("Workers.DurableObjectStorage", "TransactionSync")] = Direct("transactionSync"),
            [Key("Workers.DurableObjectSqlStorage", "Exec")] = Direct("exec"),
            [Key("Workers.DurableObjectSqlCursor<T>", "One")] = Direct("one"),
            [Key("Workers.DurableObjectSqlCursor<T>", "ToArray")] = Direct("toArray"),
            [Key("Workers.DurableObjectKvStorage", "Get")] = new("get", BindingIntrinsicKind.DurableObjectGet),
            [Key("Workers.DurableObjectKvStorage", "Put")] = Direct("put"),
            [Key("Workers.DurableObjectKvStorage", "Delete")] = Direct("delete"),
            [Key("Workers.DurableObjectKvStorage", "List")] = new("list", BindingIntrinsicKind.DictionaryObject),
            [Key("Workers.DurableObjectTransaction", "GetAsync")] = new("get", BindingIntrinsicKind.DurableObjectGet),
            [Key("Workers.DurableObjectTransaction", "PutAsync")] = Direct("put"),
            [Key("Workers.DurableObjectTransaction", "DeleteAsync")] = Direct("delete"),
            [Key("Workers.DurableObjectTransaction", "ListAsync")] = new("list", BindingIntrinsicKind.DictionaryObject),
            [Key("Workers.DurableObjectTransaction", "Rollback")] = Direct("rollback"),
            [Key("Workers.DurableObjectContainer", "GetRunningAsync")] = new("running", BindingIntrinsicKind.Property),
            [Key("Workers.DurableObjectContainer", "StartAsync")] = Direct("start"),
            [Key("Workers.DurableObjectContainer", "DestroyAsync")] = Direct("destroy"),
            [Key("Workers.DurableObjectContainer", "SignalAsync")] = Direct("signal"),
            [Key("Workers.DurableObjectContainer", "MonitorAsync")] = Direct("monitor"),
            [Key("Workers.DurableObjectContainer", "InterceptOutboundHttpAsync")] = Direct("interceptOutboundHttp"),
            [Key("Workers.DurableObjectContainer", "InterceptAllOutboundHttpAsync")] = Direct("interceptAllOutboundHttp"),
            [Key("Workers.DurableObjectContainer", "InterceptOutboundHttpsAsync")] = Direct("interceptOutboundHttps"),
            [Key("Workers.DurableObjectContainer", "ExecAsync")] = Direct("exec"),
            [Key("Workers.DurableObjectContainer", "GetTcpPort")] = Direct("getTcpPort"),
            [Key("Workers.ContainerTcpPort", "FetchAsync")] = Direct("fetch"),
            [Key("Workers.ContainerTcpPort", "ConnectAsync")] = Direct("connect"),
            [Key("Workers.ContainerExecProcess", "OutputAsync")] = Direct("output"),
            [Key("Workers.ContainerExecProcess", "GetExitCodeAsync")] = Direct("getExitCode"),
            [Key("Workers.ContainerExecProcess", "KillAsync")] = Direct("kill"),
            [Key("Workers.ContainerExecProcess", "DisposeAsync")] = new("", BindingIntrinsicKind.Dispose),

        };
}
