<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <WorkersUseProjectReference>true</WorkersUseProjectReference>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\src\Workers.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\src\Compiler\Compiler.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

</Project>
