using System.Text;

internal static class AspNetJavaScriptEmitter
{
    public static string Emit(AspNetApplication application)
    {
        var output = new StringBuilder("// Generated by Workers.Compiler.\n");
        var handlers = application.Endpoints
            .Select((endpoint, index) => new AspNetEndpointEmitter(endpoint, index).Emit())
            .ToArray();
        foreach (var handler in handlers)
            output.Append(handler.Declaration);

        output.AppendLine("async function fetch(request, env, ctx) {");
        output.AppendLine("  const url = new URL(request.url);");
        output.AppendLine("  const allowed = new Set();");
        foreach (var handler in handlers)
        {
            output.Append("  { const match = url.pathname.match(")
                .Append(handler.RegexLiteral).AppendLine(");");
            output.Append("    if (match && request.method === ")
                .Append(AspNetJavaScript.String(handler.HttpMethod)).Append(") return ")
                .Append(handler.Name).AppendLine("(request, env, ctx, url, match);");
            output.Append("    if (match) allowed.add(")
                .Append(AspNetJavaScript.String(handler.HttpMethod)).AppendLine("); }");
        }
        output.AppendLine("  if (allowed.size) return new Response(null, { status: 405, headers: { allow: [...allowed].join(\", \" ) } });");
        output.AppendLine("  return new Response(null, { status: 404 });");
        output.AppendLine("}");
        output.AppendLine("export default { fetch };");
        return output.ToString();
    }
}

internal sealed record EmittedAspNetEndpoint(
    string Name,
    string HttpMethod,
    string RegexLiteral,
    string Declaration);
