name = "workers-example-queue-consumer"
main = "dist/worker.js"
compatibility_date = "2026-06-30"

[build]
command = "dotnet publish -c Release -p:NuGetAudit=false"

[[queues.consumers]]
queue = "workers-example-jobs"
